/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form InterfazSimple
     */
    public Calculadora() {
        initComponents();
        this.setTitle("Calculadora simple");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOperaciones = new javax.swing.ButtonGroup();
        jPanelGeneral = new javax.swing.JPanel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jButtonSuma = new javax.swing.JButton();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextFieldNumero2 = new javax.swing.JTextField();
        jButtonResta = new javax.swing.JButton();
        jButtonMultiplica = new javax.swing.JButton();
        jButtonDividir = new javax.swing.JButton();
        jLabelResultadoTitulo = new javax.swing.JLabel();
        jTextFieldResultado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonCalcular = new javax.swing.JButton();
        jRadioButtonExponencial = new javax.swing.JRadioButton();
        jRadioButtonProductorio = new javax.swing.JRadioButton();
        jRadioButtonSumatorio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelNumero.setText("Número 1:");

        jTextFieldNumero.setText("Introduce número...");

        jButtonSuma.setText("+");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });

        jLabelNumero2.setText("Número 2:");

        jTextFieldNumero2.setText("Introduce número...");
        jTextFieldNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumero2ActionPerformed(evt);
            }
        });

        jButtonResta.setText("-");
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });

        jButtonMultiplica.setText("*");
        jButtonMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicaActionPerformed(evt);
            }
        });

        jButtonDividir.setText("/");
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });

        jLabelResultadoTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResultadoTitulo.setText("Resultado:");

        jTextFieldResultado.setEditable(false);
        jTextFieldResultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldResultado.setText("jTextField1");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonCalcular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCalcular.setText("Calcular...");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        buttonGroupOperaciones.add(jRadioButtonExponencial);
        jRadioButtonExponencial.setText("Exponencial");

        buttonGroupOperaciones.add(jRadioButtonProductorio);
        jRadioButtonProductorio.setText("Productorio");

        buttonGroupOperaciones.add(jRadioButtonSumatorio);
        jRadioButtonSumatorio.setSelected(true);
        jRadioButtonSumatorio.setText("Sumatorio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCalcular)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonSumatorio)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonProductorio)))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonExponencial)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSumatorio)
                    .addComponent(jRadioButtonProductorio)
                    .addComponent(jRadioButtonExponencial))
                .addGap(18, 18, 18)
                .addComponent(jButtonCalcular)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                .addComponent(jLabelNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                .addComponent(jLabelNumero2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButtonSuma)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonResta)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMultiplica)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDividir))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabelResultadoTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldResultado)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero))
                .addGap(5, 5, 5)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero2))
                .addGap(18, 18, 18)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDividir)
                    .addComponent(jButtonMultiplica)
                    .addComponent(jButtonResta)
                    .addComponent(jButtonSuma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResultadoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        try {
		int num1 = Integer.parseInt(jTextFieldNumero.getText());
                int num2 = Integer.parseInt(jTextFieldNumero2.getText());
                int suma = num1 + num2;
		jTextFieldResultado.setText(String.valueOf(suma));
	
        } catch (NumberFormatException nfe){
		jTextFieldResultado.setText("No es un número entero!");
	}
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jTextFieldNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumero2ActionPerformed

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed
        try {
		int num1 = Integer.parseInt(jTextFieldNumero.getText());
                int num2 = Integer.parseInt(jTextFieldNumero2.getText());
                int resta = num1 - num2;
		jTextFieldResultado.setText(String.valueOf(resta));
	
        } catch (NumberFormatException nfe){
		jTextFieldResultado.setText("No es un número entero!");
	}        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButtonMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicaActionPerformed
        try {
		int num1 = Integer.parseInt(jTextFieldNumero.getText());
                int num2 = Integer.parseInt(jTextFieldNumero2.getText());
                int multiplicacion = num1 * num2;
		jTextFieldResultado.setText(String.valueOf(multiplicacion));
	
        } catch (NumberFormatException nfe){
		jTextFieldResultado.setText("No es un número entero!");
	}        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMultiplicaActionPerformed

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
      try {
		int num1 = Integer.parseInt(jTextFieldNumero.getText());
                int num2 = Integer.parseInt(jTextFieldNumero2.getText());
                int division = num1 / num2;
		jTextFieldResultado.setText(String.valueOf(division));
	
        } catch (NumberFormatException nfe){
		jTextFieldResultado.setText("No es un número entero!");
	} catch (ArithmeticException e){
                jTextFieldResultado.setText("No se puede dividir por cero!");
        } 
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        if(jRadioButtonSumatorio.isSelected())
            sumatorio();
        else if(jRadioButtonProductorio.isSelected())
            productorio();
        else 
            exponencial();
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    public void sumatorio(){
        try {
		int num1 = Integer.parseInt(jTextFieldNumero.getText());
                int num2 = Integer.parseInt(jTextFieldNumero2.getText());
                int sumatorio = 0;
                
                for(int i = num1; i <= num2; i++)
                    sumatorio += i;         
            
		jTextFieldResultado.setText(String.valueOf(sumatorio));
	
        } catch (NumberFormatException nfe){
		jTextFieldResultado.setText("No es un número entero!");
        } 
    }
    
    public void productorio(){
        try {
		int num1 = Integer.parseInt(jTextFieldNumero.getText());
                int num2 = Integer.parseInt(jTextFieldNumero2.getText());
                int productorio = 1;
                
                for(int i = num1; i <= num2; i++)
                    productorio *= i;         
            
		jTextFieldResultado.setText(String.valueOf(productorio));
	
        } catch (NumberFormatException nfe){
		jTextFieldResultado.setText("No es un número entero!");
        } 
    }
    
    public void exponencial(){
        try {
		int num1 = Integer.parseInt(jTextFieldNumero.getText());
                int num2 = Integer.parseInt(jTextFieldNumero2.getText());
                
                int exp = (int)Math.pow(num1, num2);
                     
		jTextFieldResultado.setText(String.valueOf(exp));
	
        } catch (NumberFormatException nfe){
		jTextFieldResultado.setText("No es un número entero!");
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try{
 
            Calculadora.setDefaultLookAndFeelDecorated(true);
            //JDialog.setDefaultLookAndFeelDecorated(true);
            //javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            //javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        }
        catch (Exception e){
            e.printStackTrace();
        }
        
        
        
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOperaciones;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonMultiplica;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelResultadoTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JRadioButton jRadioButtonExponencial;
    private javax.swing.JRadioButton jRadioButtonProductorio;
    private javax.swing.JRadioButton jRadioButtonSumatorio;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldNumero2;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
