
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class TPVHamburger extends javax.swing.JFrame {
    ArrayList<Pedido> pedidos = new ArrayList<>();
    float preciobase = 8, pbruto, iva, pvp;
    float ternera = 0, vegana = 0, centeno = 0, gajo = 0, hdoble = 0, queso = 0, patatas = 0, ketchup, barbacoa, mostaza, adicional = 0, domicilio = 0;
    boolean tern = false, veg = false, cent = false, gaj = false, hdob = false, ques = false, pat = false, domic = false;
    boolean descuento = false;

    /**
     * Creates new form TPVHamburger
     */
    public TPVHamburger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGBurger = new javax.swing.ButtonGroup();
        btGPan = new javax.swing.ButtonGroup();
        btGPatatas = new javax.swing.ButtonGroup();
        btGEntrega = new javax.swing.ButtonGroup();
        jLabelTituloAPP = new javax.swing.JLabel();
        jPanelBurger = new javax.swing.JPanel();
        jRadioButtonPollo = new javax.swing.JRadioButton();
        jRadioButtonCerdo = new javax.swing.JRadioButton();
        jRadioButtonTernera = new javax.swing.JRadioButton();
        jRadioButtonVegana = new javax.swing.JRadioButton();
        jPanelPan = new javax.swing.JPanel();
        jRadioButtonPanNormal = new javax.swing.JRadioButton();
        jRadioButtonIntegral = new javax.swing.JRadioButton();
        jRadioButtonCenteno = new javax.swing.JRadioButton();
        jPanelPatatas = new javax.swing.JPanel();
        jRadioButtonFritas = new javax.swing.JRadioButton();
        jRadioButtonGajo = new javax.swing.JRadioButton();
        jPanelAdicionales = new javax.swing.JPanel();
        jCheckBoxBurgerDoble = new javax.swing.JCheckBox();
        jCheckBoxExtraQueso = new javax.swing.JCheckBox();
        jCheckBoxExtraPatatas = new javax.swing.JCheckBox();
        jSpinnerKetchup = new javax.swing.JSpinner();
        jLabelKetchup = new javax.swing.JLabel();
        jLabelBarbacoa = new javax.swing.JLabel();
        jSpinnerBarbacoa = new javax.swing.JSpinner();
        jLabelMostaza = new javax.swing.JLabel();
        jSpinnerMostaza = new javax.swing.JSpinner();
        jLabelAdicional = new javax.swing.JLabel();
        jTextFieldAdicional = new javax.swing.JTextField();
        jPanelOpFinales = new javax.swing.JPanel();
        jRadioButtonDomicilio = new javax.swing.JRadioButton();
        jRadioButtonLocal = new javax.swing.JRadioButton();
        jCheckBoxDescuento = new javax.swing.JCheckBox();
        jButtonCalcular = new javax.swing.JButton();
        jLabelPrecioBruto = new javax.swing.JLabel();
        jTextFieldPrecioBruto = new javax.swing.JTextField();
        jTextFieldIVA = new javax.swing.JTextField();
        jLabelIVA = new javax.swing.JLabel();
        jTextFieldPVP = new javax.swing.JTextField();
        jLabelPVP = new javax.swing.JLabel();
        jButtonGuardarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPV Gestión de Hamburguesería");
        setResizable(false);

        jLabelTituloAPP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTituloAPP.setText("TPV Gestión de Hamburguesería");

        jPanelBurger.setBorder(javax.swing.BorderFactory.createTitledBorder("Hamburguesa"));

        btGBurger.add(jRadioButtonPollo);
        jRadioButtonPollo.setSelected(true);
        jRadioButtonPollo.setText("Pollo");

        btGBurger.add(jRadioButtonCerdo);
        jRadioButtonCerdo.setText("Cerdo");

        btGBurger.add(jRadioButtonTernera);
        jRadioButtonTernera.setText("Ternera (+1€)");

        btGBurger.add(jRadioButtonVegana);
        jRadioButtonVegana.setText("Vegana (+1€)");

        javax.swing.GroupLayout jPanelBurgerLayout = new javax.swing.GroupLayout(jPanelBurger);
        jPanelBurger.setLayout(jPanelBurgerLayout);
        jPanelBurgerLayout.setHorizontalGroup(
            jPanelBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBurgerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonVegana)
                    .addComponent(jRadioButtonTernera)
                    .addComponent(jRadioButtonCerdo)
                    .addComponent(jRadioButtonPollo))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelBurgerLayout.setVerticalGroup(
            jPanelBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBurgerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonPollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCerdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonTernera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonVegana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPan.setBorder(javax.swing.BorderFactory.createTitledBorder("Pan"));

        btGPan.add(jRadioButtonPanNormal);
        jRadioButtonPanNormal.setSelected(true);
        jRadioButtonPanNormal.setText("Normal");

        btGPan.add(jRadioButtonIntegral);
        jRadioButtonIntegral.setText("Integral");

        btGPan.add(jRadioButtonCenteno);
        jRadioButtonCenteno.setText("Centeno (+0,25€)");

        javax.swing.GroupLayout jPanelPanLayout = new javax.swing.GroupLayout(jPanelPan);
        jPanelPan.setLayout(jPanelPanLayout);
        jPanelPanLayout.setHorizontalGroup(
            jPanelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonIntegral)
                    .addComponent(jRadioButtonPanNormal)
                    .addComponent(jRadioButtonCenteno))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelPanLayout.setVerticalGroup(
            jPanelPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonPanNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonIntegral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCenteno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPatatas.setBorder(javax.swing.BorderFactory.createTitledBorder("Patatas"));

        btGPatatas.add(jRadioButtonFritas);
        jRadioButtonFritas.setSelected(true);
        jRadioButtonFritas.setText("Fritas");

        btGPatatas.add(jRadioButtonGajo);
        jRadioButtonGajo.setText("Gajo (+0,5€)");

        javax.swing.GroupLayout jPanelPatatasLayout = new javax.swing.GroupLayout(jPanelPatatas);
        jPanelPatatas.setLayout(jPanelPatatasLayout);
        jPanelPatatasLayout.setHorizontalGroup(
            jPanelPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatatasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonGajo)
                    .addComponent(jRadioButtonFritas))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelPatatasLayout.setVerticalGroup(
            jPanelPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatatasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonFritas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonGajo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAdicionales.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones adicionales"));

        jCheckBoxBurgerDoble.setText("Hamburguesa doble (+2€)");

        jCheckBoxExtraQueso.setText("Extra de queso (+0,5€)");

        jCheckBoxExtraPatatas.setText("Extra de patatas (+1€)");

        jSpinnerKetchup.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));

        jLabelKetchup.setText("Ketchup");

        jLabelBarbacoa.setText("Barbacoa");

        jSpinnerBarbacoa.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));

        jLabelMostaza.setText("Mostaza");

        jSpinnerMostaza.setModel(new javax.swing.SpinnerNumberModel(0, null, 10, 1));

        jLabelAdicional.setText("Producto adicional (precio):");

        jTextFieldAdicional.setText("0");

        javax.swing.GroupLayout jPanelAdicionalesLayout = new javax.swing.GroupLayout(jPanelAdicionales);
        jPanelAdicionales.setLayout(jPanelAdicionalesLayout);
        jPanelAdicionalesLayout.setHorizontalGroup(
            jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdicionalesLayout.createSequentialGroup()
                        .addGroup(jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxExtraQueso)
                            .addComponent(jCheckBoxBurgerDoble)
                            .addComponent(jCheckBoxExtraPatatas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdicionalesLayout.createSequentialGroup()
                                .addComponent(jLabelKetchup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdicionalesLayout.createSequentialGroup()
                                .addComponent(jLabelBarbacoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdicionalesLayout.createSequentialGroup()
                                .addComponent(jLabelMostaza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(jPanelAdicionalesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelAdicional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelAdicionalesLayout.setVerticalGroup(
            jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxBurgerDoble)
                    .addGroup(jPanelAdicionalesLayout.createSequentialGroup()
                        .addGroup(jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelKetchup)
                            .addComponent(jSpinnerKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBarbacoa)
                            .addComponent(jSpinnerBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxExtraQueso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMostaza)
                            .addComponent(jSpinnerMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxExtraPatatas))))
                .addGap(18, 18, 18)
                .addGroup(jPanelAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdicional))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelOpFinales.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones finales"));

        btGEntrega.add(jRadioButtonDomicilio);
        jRadioButtonDomicilio.setText("Reparto domicilio (+1€)");

        btGEntrega.add(jRadioButtonLocal);
        jRadioButtonLocal.setSelected(true);
        jRadioButtonLocal.setText("Recogida en local");

        jCheckBoxDescuento.setText("Aplicar descuento (-20%)");

        javax.swing.GroupLayout jPanelOpFinalesLayout = new javax.swing.GroupLayout(jPanelOpFinales);
        jPanelOpFinales.setLayout(jPanelOpFinalesLayout);
        jPanelOpFinalesLayout.setHorizontalGroup(
            jPanelOpFinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpFinalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpFinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonLocal)
                    .addComponent(jRadioButtonDomicilio)
                    .addComponent(jCheckBoxDescuento))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelOpFinalesLayout.setVerticalGroup(
            jPanelOpFinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpFinalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDomicilio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxDescuento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCalcular.setText("Calcular precio");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelPrecioBruto.setText("Precio total bruto:");

        jLabelIVA.setText("Valor de IVA (4%): ");

        jLabelPVP.setText("PVP:");

        jButtonGuardarPedido.setText("Almacenar pedido");
        jButtonGuardarPedido.setEnabled(false);
        jButtonGuardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPedidoActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabelTituloAPP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jPanelPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelOpFinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGuardarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPrecioBruto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPrecioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabelIVA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabelPVP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPVP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloAPP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOpFinales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecioBruto)
                    .addComponent(jTextFieldPrecioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIVA)
                    .addComponent(jTextFieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPVP)
                    .addComponent(jTextFieldPVP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        
        if(jRadioButtonTernera.isSelected()){
            ternera = 1; tern = true; jTextArea1.append("Carne: ternera");
        }
        if(jRadioButtonVegana.isSelected()){
            vegana = 1; veg = true;
        }
        if(jRadioButtonCenteno.isSelected()){
            centeno = 0.25f; cent = true;
        }
        if(jRadioButtonGajo.isSelected()){
            gajo = 0.5f; gaj = true;
        }
        if(jCheckBoxBurgerDoble.isSelected()){
            hdoble = 2; hdob = true;
        }
        if(jCheckBoxExtraQueso.isSelected()){
            queso = 0.5f; ques = true;
        }
        if(jCheckBoxExtraPatatas.isSelected()){
            patatas = 1; pat = true;
        }
        if(jRadioButtonDomicilio.isSelected()){
            domicilio = 1; domic = true;
        }
        
        ketchup = (int)jSpinnerKetchup.getValue();
        barbacoa = (int)jSpinnerBarbacoa.getValue();
        mostaza = (int)jSpinnerMostaza.getValue();
        
        try{
            if(!jTextFieldAdicional.getText().equals(""))
                adicional = Float.parseFloat(jTextFieldAdicional.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"¡Sólo valores numéricos en el producto adicional!","ERROR",JOptionPane.WARNING_MESSAGE);
        }
        
        pbruto = preciobase + ternera + vegana + centeno + gajo + hdoble + queso + patatas + (ketchup + barbacoa + mostaza)*0.25f + adicional + domicilio;
        
        if(jCheckBoxDescuento.isSelected()){ //Si casilla descuento marcada lo aplicamos
            pbruto = pbruto * 0.8f;
            descuento = true;
        }
        
        iva = pbruto * 0.04f;
        pvp = pbruto + iva;
        
        jTextFieldPrecioBruto.setText("" + pbruto);
        jTextFieldIVA.setText("" + iva);
        jTextFieldPVP.setText("" + pvp);
        jButtonGuardarPedido.setEnabled(true);
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPedidoActionPerformed
        int numpeds = pedidos.size();
        Pedido p;
        p = new Pedido(numpeds+1,tern,veg,cent,gaj,hdob,ques,pat,(int)ketchup,(int)barbacoa,(int)mostaza,adicional,domic,descuento,pbruto,iva,pvp);
        pedidos.add(p);
    }//GEN-LAST:event_jButtonGuardarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPVHamburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPVHamburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPVHamburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPVHamburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPVHamburger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGBurger;
    private javax.swing.ButtonGroup btGEntrega;
    private javax.swing.ButtonGroup btGPan;
    private javax.swing.ButtonGroup btGPatatas;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonGuardarPedido;
    private javax.swing.JCheckBox jCheckBoxBurgerDoble;
    private javax.swing.JCheckBox jCheckBoxDescuento;
    private javax.swing.JCheckBox jCheckBoxExtraPatatas;
    private javax.swing.JCheckBox jCheckBoxExtraQueso;
    private javax.swing.JLabel jLabelAdicional;
    private javax.swing.JLabel jLabelBarbacoa;
    private javax.swing.JLabel jLabelIVA;
    private javax.swing.JLabel jLabelKetchup;
    private javax.swing.JLabel jLabelMostaza;
    private javax.swing.JLabel jLabelPVP;
    private javax.swing.JLabel jLabelPrecioBruto;
    private javax.swing.JLabel jLabelTituloAPP;
    private javax.swing.JPanel jPanelAdicionales;
    private javax.swing.JPanel jPanelBurger;
    private javax.swing.JPanel jPanelOpFinales;
    private javax.swing.JPanel jPanelPan;
    private javax.swing.JPanel jPanelPatatas;
    private javax.swing.JRadioButton jRadioButtonCenteno;
    private javax.swing.JRadioButton jRadioButtonCerdo;
    private javax.swing.JRadioButton jRadioButtonDomicilio;
    private javax.swing.JRadioButton jRadioButtonFritas;
    private javax.swing.JRadioButton jRadioButtonGajo;
    private javax.swing.JRadioButton jRadioButtonIntegral;
    private javax.swing.JRadioButton jRadioButtonLocal;
    private javax.swing.JRadioButton jRadioButtonPanNormal;
    private javax.swing.JRadioButton jRadioButtonPollo;
    private javax.swing.JRadioButton jRadioButtonTernera;
    private javax.swing.JRadioButton jRadioButtonVegana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerBarbacoa;
    private javax.swing.JSpinner jSpinnerKetchup;
    private javax.swing.JSpinner jSpinnerMostaza;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAdicional;
    private javax.swing.JTextField jTextFieldIVA;
    private javax.swing.JTextField jTextFieldPVP;
    private javax.swing.JTextField jTextFieldPrecioBruto;
    // End of variables declaration//GEN-END:variables
}
